### ISSUE TITLE
Time sort

### ISSUE THREAD

**Issue by sasscanoodle** [pavelk2/social-feed#95] opened 2015-06-02 16:52 UTC
Is there a way to display the info based on time, not in order of social network as seems to be now. Right now it shows them based on time but all instagrams then all twitters, then all facebook. I am looking for facebook, instagram, instagram, twitter, facebook, twitter, twitter as they are listed based on the time they were posted solely regardless of network.

**Comment by pavelk2** [comment] 2015-06-02 19:17
Which web-browser do you use?

In social-feed the posts are sorted by date independent to the social-network they belong to http://pavelk2.github.io/social-feed/.
I checked in Chrome - it works correct, please let me know in which browser you experience a problem.

**Comment by pavelk2** [comment] 2015-06-17 07:22
Duplicate with https://github.com/pavelk2/social-feed/issues/26

**Comment by club-silencio** [comment] 2015-06-25 17:21
I'm seeing this issue as well on Safari 8.0.6 & Chrome 43.0.2357.130 (64-bit) on Mac. The feed seems to be sorted by network, then time.

**Comment by pavelk2** [comment] 2015-06-25 19:04
It is strange, as I can not replicate the error:

#### Safari

Version 8.0.6 (10600.6.3)

https://www.dropbox.com/s/v8j6oqwk5vnv14w/Screenshot%202015-06-25%2021.02.28.png?dl=0

#### Chrome

Version 43.0.2357.124 (64-bit)

https://www.dropbox.com/s/9c9l3o43s5mjjtj/Screenshot%202015-06-25%2021.04.28.png?dl=0

**Comment by yp28** [comment] 2015-11-19 09:12
Issue can be replicated on Linux Ubuntu 14.04 LTS, Google Chrome Version 46.0.2490.86, and Windows 7, Chrome (version unknown, one of the latest).

**Comment by yp28** [comment] 2015-11-19 09:40
Why is the callback commented out? Using the callback you could sort it by adding a data-date attribute containing the unix date, then ordering the DOM by that.

**Comment by Webarkitekt** [comment] 2015-11-19 11:46
@YP28 You mean adding a data-timestamp attribute, i think that is the best way to do it.

**Comment by yp28** [comment] 2015-11-19 12:46
@Webarkitekt, naming difference, same feature. Timestamp is a better fit though.

**Comment by Webarkitekt** [comment] 2015-11-19 12:54
This attribute already exists as dt_create, in the tpl : `dt-create="{{=it.dt_create}}"` i cannot reproduce this issue all posts are ordered by date (last first) when the attribute is set.

**Comment by yp28** [comment] 2015-11-19 12:56
Try removing the attribute from the template, see what happens. I have a hunch it orders the DOM after already building it up, using the dt-create attribute. 

That's a bad practice if you ask me. The output should be ordered before even appending the HTML to the document.

_Edit:_ and indeed [it does](https://github.com/pavelk2/social-feed/blob/gh-pages/js/jquery.socialfeed.js#L126).

**Comment by pavelk2** [comment] 2015-11-19 13:00
Guys, please make sure you use the same browser to test out whether it works or not

**Comment by Webarkitekt** [comment] 2015-11-19 13:05
@YP28  Of course if the dt-create attribute isn't present, the ordering will not work. So you want to add a loader to show all the posts in the correct order instantly ?
@pavelk2 i don't think this is an issue about the order function and browser, but more like an enhancement

**Comment by yp28** [comment] 2015-11-19 13:07
I'm using a custom template, which is why it's failing. I don't set the dt-create attribute since I don't need it, and it was unknown to me this was used to order the feed.

@Webarkitekt, I think it shouldn't be that hard to do the ordering before spitting out the HTML. Instead of rendering we could write all items to an array with the date as a key, and do a simple sort on it.

**Comment by Webarkitekt** [comment] 2015-11-19 13:16
@YP28 It's an enhancement so i close this issue.

**Closed as completed** 2015-11-19 13:15 UTC

**Comment by pavelk2** [comment] 2015-11-19 13:24
@YP28 @Webarkitekt Still I think that we need to keep track of the enhancements to be done, so we have a back log of things to implement.
