### ISSUE TITLE
Subfolder name in links and src

### ISSUE THREAD

**Issue by ghost** [pavelk2/social-feed#128] opened 2015-10-19 18:33 UTC
Trying to make joomla module using your plugin. I have site in subfolder called "Master/", problem is that  subfolder name apears in links and image src. 

this:

```
{{=it.author_link}}
```

gives me this:
`/Master/http://twitter.com/user_name"`

And this:
`{{=it.author_picture}}`
gives me this:
/Master/http://pbs.twimg.com/profile_images/624826963895681024/yOrwvZ9o_normal.jpg

Tryed to remove /Master/ from the attribute with jquery bit dosen't works.

**Comment by pavelk2** [comment] 2015-11-26 23:02
This is more the question to Joomla community - how to make your links absolute rather than relative. I will close the issue. Let me know later on if the issue is still up.

**Closed as completed by pavelk2** 2015-11-26 23:02 UTC
Labels: question
